### ISSUE TITLE
Unable to deploy to vercel

### ISSUE THREAD

**Issue by ahmednrana** [lachlanhawthorne/tamagui-supabase-todos-quickstart#1]
I clicked on deploy to Vercel and it gives the following error.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/21101759/174290755-fe655046-dd3c-471f-8280-778561423ecb.png">

**Comment by ivopr** [comment]
I think the Path is not 'apps/next' only 'next'

**Comment by lachlanhawthorne** [comment]
I've updated the README so the Vercel deploy button will work with this repo
